### ISSUE TITLE
NoMethodError: undefined method `alias_method_chain' for ActionDispatch::Request:Class

### ISSUE THREAD

**Issue by sumitsinghnaruka** [igor-alexandrov/wiselinks#114]
I facing this issue after install wiselinks gem.
Ruby -v  Ruby 2.4.0
Rails  -v  Rails 5.1.3

rake aborted!
NoMethodError: undefined method `alias_method_chain' for ActionDispatch::Request:Class
/home/wscube/.rvm/gems/ruby-2.4.0/gems/wiselinks-1.2.1/lib/wiselinks/request.rb:4:in `included'
/home/wscube/.rvm/gems/ruby-2.4.0/gems/wiselinks-1.2.1/lib/wiselinks/rails.rb:9:in `include'
/home/wscube/.rvm/gems/ruby-2.4.0/gems/wiselinks-1.2.1/lib/wiselinks/rails.rb:9:in `block in <class:Engine>'
/home/wscube/.rvm/gems/ruby-2.4.0/gems/railties-5.1.3/lib/rails/initializable.rb:30:in `instance_exec'
/home/wscube/.rvm/gems/ruby-2.4.0/gems/railties-5.1.3/lib/rails/initializable.rb:30:in `run'
/home/wscube/.rvm/gems/ruby-2.4.0/gems/railties-5.1.3/lib/rails/initializable.rb:59:in `block in run_initializers'
/home/wscube/.rvm/gems/ruby-2.4.0/gems/railties-5.1.3/lib/rails/initializable.rb:58:in `run_initializers'
/home/wscube/.rvm/gems/ruby-2.4.0/gems/railties-5.1.3/lib/rails/application.rb:353:in `initialize!'
/home/wscube/Upstge/upstge-latest-version/config/environment.rb:5:in `<top (required)>'
/home/wscube/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/home/wscube/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/home/wscube/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/wscube/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/home/wscube/.rvm/gems/ruby-2.4.0/gems/railties-5.1.3/lib/rails/application.rb:329:in `require_environment!'
/home/wscube/.rvm/gems/ruby-2.4.0/gems/railties-5.1.3/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/home/wscube/.rvm/gems/ruby-2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/home/wscube/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/wscube/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/home/wscube/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by alexvirtualbr** [comment]
[SOLVED] Hey guys, here i'm the same problem:
- ruby 2.6.0preview2 (2018-05-31 trunk 63539) [x86_64-linux]
- Rails 5.2.1

.../.rvm/gems/ruby-2.6.0-preview2@rails520/gems/wiselinks-1.2.1/lib/wiselinks/request.rb:4:in `included': undefined method `alias_method_chain' for ActionDispatch::Request:Class (NoMethodError)
Did you mean?  alias_method

--------------------------------------------------------
Solved after I appleyd this changes.
